Automation to generate component diagrams with plantUML for edx platforms in GitHub Actions.
eol-uchile/edx-staging pull request #771
Opened 2023-12-04 17:04 UTC by matiasua

2023-12-04 17:14 UTC, fsologureng commented
Gran trabajo @matiasua !

2023-12-04 17:18 UTC, fsologureng commented on .github/workflows/diagram.yml
> +      username:
Esta definición es requerida para el reuso del workflow por parte de otros repos?

2023-12-04 17:38 UTC, matiasua commented on .github/workflows/diagram.yml
> +      username:
Correcto, es requerida para la llamada por parte de los otros repos.

Me faltó documentar con un comments ese paso.

2023-12-04 18:15 UTC, fsologureng requested changes
Muy buen trabajo compañero, considerando el resultado y el trabajo con el rebase de tus commits.

Por si acaso, los detalles que te pido (y los que te sugiero si los quieres abordar) basta con que los agregues a un nuevo commit; No es necesario más rebase.

2023-12-04 18:15 UTC, fsologureng commented on .github/workflows/diagram.yml
> +      run: python3 gen_deps_diagram.py
Detalle menor: Usar `python` en vez de `python3` para ser coherente con linea 49.

2023-12-04 18:15 UTC, fsologureng commented on .github/workflows/diagram.yml
> +        if [[ $(git status --porcelain) ]]; then
Cambiar a un esquema donde el step no se realice si no se dan las condiciones (evaluación del if), para que sea más sencillo visualizar en el log que el commit no se hizo.
Como referencia ver https://github.com/eol-uchile/edx-platform/blob/eol/koa.master/.github/workflows/docker.yml#L71

2023-12-04 18:15 UTC, fsologureng commented on .github/workflows/diagram.yml
> +name: generate diagram
Usar nombre con Mayúsculas como los demás workflows del repo.

2023-12-04 18:15 UTC, fsologureng commented on .mergify.yml
Cambio no vinculado con la funcionalidad. Idealmente sacar del PR.

2023-12-04 18:15 UTC, fsologureng commented on diagrams/diagram.puml
Este archivo será sobreescrito por el workflow en un commit inmediatamente posterior al merge.
Sacar del PR pues es innecesario.

2023-12-04 18:15 UTC, fsologureng commented on diagrams/diagram.svg
Idem anterior. Archivo será sobreescrito por merge del pr por el propio workflow.

2023-12-04 18:15 UTC, fsologureng commented on gen_deps_diagram.py
> +        return {'url': url, 'base_image': base_image_tag}
Comentario menor y no exigencia: por qué acá devuelves un diccionario y para el Dockerfile devuelves 2 variables? por qué no un criterio único para 2 funciones que son muy similares?
Incluso podría usarse el esquema de extracción y poblamiento de `process_themes`: pasar la referencia al diccionario `data` y agregarle los datos que le corresponde a cada método.

2023-12-04 18:15 UTC, fsologureng commented on gen_deps_diagram.py
> +def main():
comentario no exigencia: es buena práctica dejar la definición del código ejecutable (main) al final del archivo, y las definiciones de los métodos usados, antes de que se llamen.

2023-12-04 18:15 UTC, fsologureng commented on gen_deps_diagram.py
> +def extract_info_from_txt(txt_file_path):
Comentario no exigencia: Este código y su caller (process_txt_file) se puede factorizar en 1 solo, de modo de no generar el diccionario `packages` (linea 105) para después recorrerlo; Cuando la ejecución está analizando la linea correspondiente del archivo .txt, ya puede poblar el diccionario data inmediatamente (si lo tiene al alcance).

2023-12-04 18:15 UTC, fsologureng commented on gen_deps_diagram.py
> +        'has_links': has_links
Esta variable no se usa y me parece que no es necesaria en todo el código.

2023-12-04 18:15 UTC, fsologureng commented on templates/diagram_template.j2
> +                Container({{requirement.basename}}{{loop.index}}, "{{package.name}}", $link="{{package.link}}")
Se está generando un link que apunta a `None` para el caso de los `python_packages`.
Probablemente se puede usar un `if` en jinja para ponerle o no link al `C4Container` según si viene definido o no, lo cual haría innecesaria la variable `has_links` del .py.

2023-12-04 19:02 UTC, matiasua commented on .github/workflows/diagram.yml
> +      run: python3 gen_deps_diagram.py
La configuración del entorno de Python está establecida para Python 3. No estoy seguro de si reemplazar 'python3' por 'python' funcionará como esperamos.

2023-12-05 12:13 UTC, matiasua commented on diagrams/diagram.puml
Git no es capaz de versionar directorios vacios, pero existe una solucion que es un archivo .gitkeep
Estos archivos no ocupan nada, ya que están vacíos, por lo que no añaden apenas nada tampoco a la carga del remoto de Git ni a la transferencia de datos. Es como si no estuvieran. Pero como están Git los registra en el control de código y por tanto añade también la carpeta que los contiene.

2023-12-05 12:30 UTC, fsologureng commented on diagrams/diagram.puml
y para qué necesitas que estén en este pr?

2023-12-05 15:02 UTC, fsologureng approved these changes

2023-12-05 15:03 UTC, merged