feat: add edx-username-changer dependency
eol-uchile/edx-staging pull request #882
Opened 2024-10-17 19:37 UTC by matiasua

2024-10-17 20:54 UTC, tomaspemora approved these changes

2024-10-17 20:54 UTC, tomaspemora commented on requirements/apps.txt
> +-e git+https://github.com/mitodl/edx-username-changer.git@main#egg=edx-username-changer
no lo ibamos a agregar como paquete?

2024-10-18 12:34 UTC, matiasua commented on requirements/apps.txt
> +-e git+https://github.com/mitodl/edx-username-changer.git@main#egg=edx-username-changer
Done;

2024-10-18 12:53 UTC, tomaspemora requested changes

2024-10-18 12:53 UTC, tomaspemora commented on requirements/python_packages.txt
> +edx-username-changer
lo haría con edx-username-changer==0.3.1 solo para evitar que no funcione en el futuro.

2024-10-18 12:58 UTC, matiasua commented on requirements/python_packages.txt
> +edx-username-changer
Toda la razón

2024-10-18 14:34 UTC, tomaspemora approved these changes

2024-10-18 14:48 UTC, merged